# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 3 plugins to power up your Jekyll Blog
email: craigsims808@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Plugins are a powerful tool to customize and extend the functionality of your
  Strapi App. The Strapi Market is the official marketplace to find plugins comprising
  more than 60 to choose from. These plugins were developed by the Strapi team . . . 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: craigsims808
github_username:  craigsims808

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-strapi-mod
strapi:
  # Your API endpoint (optional, default to http://localhost:1337/api)
  endpoint: http://localhost:1337/api
  # Collections, key is used to access in the strapi.collections
  # template variable
  collections:
    # Example for a "posts" collection
    posts:
      # Collection name (optional). Used to construct the url requested. Example: type `foo` would generate the following url `http://localhost:1337/foo`.
      type: posts
       # Permalink used to generate the output files (eg. /posts/:id).
      permalink: /posts/:id/
      # Layout file for this collection
      # layout: post.html
      # Generate output files or not (default: false)
      # output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
